#!/bin/bash

ec2din | awk '
	BEGIN {
		FS="\t";
		printf "%4s\t%10s\t%10s\t%-40s\t%s\n", "No.", "Instance", "Sec. group", "Domain name", "Name";
	}
	
	/INSTANCE/ {
		counter++;
		inst=$2;
		domain=$4;
		sg=$29;
	}
	
	/TAG/ {
		if ( $4 == "Name") {
			name=$5;
			getline;
		} else {
			b="NULL";
		}
		
		printf "%4s\t%10s\t%10s\t%-40s\t%s\n", counter, inst,sg,domain,name;
	}
' > /tmp/server_list

cat /tmp/server_list

read -p 'Enter server number, server range (e.g. 3..5) or list of servers (e.g. 2 3 4 8 9): ' servers

if [[ $servers =~ ([0-9]+)..([0-9]+) ]]
then
	start=${BASH_REMATCH[1]}
	end=${BASH_REMATCH[2]}
	servers=$(seq $start $end)
fi

for server in $servers
do
	domain=$(awk "NR==$server+1" /tmp/server_list | awk "{print \$4}")

	echo "Ssh-ing to $domain"

	ssh $domain
done
